"""add seo reports table

Revision ID: a80ddacd7ea9
Revises: 0dfd9f1abaf6
Create Date: 2026-08-30 16:49:16.770714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a80ddacd7ea9'
down_revision: Union[str, Sequence[str], None] = '0dfd9f1abaf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seo_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('site_url', sa.String(), nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seo_reports_created_at'), 'seo_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_seo_reports_site_url'), 'seo_reports', ['site_url'], unique=False)
    op.create_index(op.f('ix_seo_reports_user_id'), 'seo_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seo_reports_user_id'), table_name='seo_reports')
    op.drop_index(op.f('ix_seo_reports_site_url'), table_name='seo_reports')
    op.drop_index(op.f('ix_seo_reports_created_at'), table_name='seo_reports')
    op.drop_table('seo_reports')
    # ### end Alembic commands ###
