"""split oauth credentials and add sessions

Revision ID: eaf2c0da876c
Revises: d1fc65570d8a
Create Date: 2026-07-23 07:01:53.828799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eaf2c0da876c'
down_revision: Union[str, Sequence[str], None] = 'd1fc65570d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_provider_user', 'oauth_accounts', ['provider', 'provider_user_id'])
    op.drop_column('oauth_accounts', 'refresh_token')
    op.drop_column('oauth_accounts', 'access_token')
    op.drop_column('oauth_accounts', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_accounts', sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('oauth_accounts', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('oauth_accounts', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_provider_user', 'oauth_accounts', type_='unique')
    # ### end Alembic commands ###
